config/routes.rb
Rails.application.routes.draw do

  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :users, path: 'admin'
  get 'posts/odd_even_filter' => 'posts#odd_even_filter', as: :odd_even_filter
  resources :posts
  post 'posts/search' => 'posts#search', as: :post_search
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_title, against: :title
  mount_uploader :post_cover, PostCoverUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # skip_before_action :verify_authenticity_token
  # protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @post = Post.new
    render layout: "admin"
  end

  def create
    @post = Post.new({title: params['title'], small_description: params["small_description"], post_cover: params["file"]["0"]})
    if @post.save
      flash[:success] = "Post saved successfuly."
      @post = Post.new
      redirect_to new_post_path
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def index
    @search_term = params["search"]
    @posts = if @search_term.present?
               Post.search_by_title(params["search"])
             else
               Post.all
             end
    @posts = @posts.order(created_at: :desc)
    if params["seq_filter"].present?
      @seq_filter = params["seq_filter"]
      mth = "#{params["seq_filter"]}?".to_sym
      @posts = @posts.partition { |r| r.id.send(mth) }.first
    end
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(30)

    respond_to do |format|
      format.js
      format.html
    end
  end

  def search
    @search_term = params["search"]
    @posts = if params["search"].present?
                Post.search_by_title(params["search"])
              else
                Post.all
              end
    @posts = @posts.order(created_at: :desc)
    if params["seq_filter"].present?
      @seq_filter = params["seq_filter"]
      mth = "#{params["seq_filter"]}?".to_sym
      @posts = @posts.partition { |r| r.id.send(mth) }.first
    end
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(30)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def odd_even_filter
    @search_term = params["search"]
    @posts = if @search_term.present?
               Post.search_by_title(params["search"])
             else
               Post.all
             end
    @posts = @posts.order(created_at: :desc)
    if params["seq_filter"].present?
      @seq_filter = params["seq_filter"]
      mth = "#{params["seq_filter"]}?".to_sym
      @posts = @posts.partition { |r| r.id.send(mth) }.first
    end
    @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(30)
    respond_to do |format|
      format.js
      format.html
    end
  end

  private

  def post_params
    params.require(:post).permit!
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout "admin"
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <!-- Latest Posts -->
    <main class="posts-listing col-lg-8">
      <div class="container">
        <div class="row">
          <!-- post -->
          <div class="post col-xl-6">
            <div class="post-thumbnail"><a href="post.html">
              <%= image_tag "blog-post-1.jpeg", alt: '', class: 'img-fluid' %>
            </a></div>
            <div class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <div class="date meta-last">20 May | 2016</div>
                <div class="category"><a href="#">Business</a></div>
              </div><a href="post.html">
                <h3 class="h4">Alberto Savoia Can Teach You About Interior</h3></a>
              <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
              <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                  <div class="avatar">
                    <%= image_tag "default_logo.png", alt: '', class: 'img-fluid' %>
                  </div>
                  <div class="title"><span>John Doe</span></div></a>
                <div class="date"><i class="icon-clock"></i> 2 months ago</div>

              </footer>
            </div>
          </div>
          <!-- post             -->
          <div class="post col-xl-6">
            <div class="post-thumbnail"><a href="post.html">
            <%= image_tag "blog-post-2.jpeg", alt: '', class: 'img-fluid' %>
            </a></div>
            <div class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <div class="date meta-last">20 May | 2016</div>
                <div class="category"><a href="#">Business</a></div>
              </div><a href="post.html">
                <h3 class="h4">Alberto Savoia Can Teach You About Interior</h3></a>
              <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
              <div class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                  <div class="avatar">
                    <%= image_tag "default_logo.png", alt: '', class: 'img-fluid' %>
                    </div>
                  <div class="title"><span>John Doe</span></div></a>
                <div class="date"><i class="icon-clock"></i> 2 months ago</div>

              </div>
            </div>
          </div>
          <!-- post             -->
          <div class="post col-xl-6">
            <div class="post-thumbnail"><a href="post.html">
              <%= image_tag "blog-post-3.jpeg", alt: '', class: 'img-fluid' %>
              </a>
            </div>
            <div class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <div class="date meta-last">20 May | 2016</div>
                <div class="category"><a href="#">Business</a></div>
              </div><a href="post.html">
                <h3 class="h4">Alberto Savoia Can Teach You About Interior</h3></a>
              <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
              <div class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                  <div class="avatar">
                    <%= image_tag "default_logo.png", alt: '', class: 'img-fluid' %>
                  </div>
                  <div class="title"><span>John Doe</span></div></a>
                <div class="date"><i class="icon-clock"></i> 2 months ago</div>

              </div>
            </div>
          </div>
          <!-- post -->
          <div class="post col-xl-6">
            <div class="post-thumbnail"><a href="post.html">
              <%= image_tag "blog-post-4.jpeg", alt: '', class: 'img-fluid' %>
            </a></div>
            <div class="post-details">
              <div class="post-meta d-flex justify-content-between">
                <div class="date meta-last">20 May | 2016</div>
                <div class="category"><a href="#">Business</a></div>
              </div><a href="post.html">
                <h3 class="h4">Alberto Savoia Can Teach You About Interior</h3></a>
              <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.</p>
              <div class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                  <div class="avatar">
                    <%= image_tag "default_logo.png", alt: '', class: 'img-fluid' %>
                    </div>
                  <div class="title"><span>John Doe</span></div></a>
                <div class="date"><i class="icon-clock"></i> 2 months ago</div>
              </div>
            </div>
          </div>
        </div>
        <!-- Pagination -->
        <nav aria-label="Page navigation example">
          <ul class="pagination pagination-template d-flex justify-content-center">
            <li class="page-item"><a href="#" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
            <li class="page-item"><a href="#" class="page-link active">1</a></li>
            <li class="page-item"><a href="#" class="page-link">2</a></li>
            <li class="page-item"><a href="#" class="page-link">3</a></li>
            <li class="page-item"><a href="#" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
          </ul>
        </nav>
      </div>
    </main>
    <aside class="col-lg-4">
      <!-- Widget [Search Bar Widget]-->
      <div class="widget search">
        <header>
          <h3 class="h6">Search the blog</h3>
        </header>
        <form action="#" class="search-form">
          <div class="form-group">
            <input type="search" placeholder="What are you looking for?">
            <button type="submit" class="submit"><i class="icon-search"></i></button>
          </div>
        </form>
      </div>
      <!-- Widget [Latest Posts Widget]        -->
      <div class="widget latest-posts">
        <header>
          <h3 class="h6">Latest Posts</h3>
        </header>
        <div class="blog-posts"><a href="#">
            <div class="item d-flex align-items-center">
              <div class="image">
                <%= image_tag 'small-thumbnail-1.jpg', alt: '', class: 'img-fluid' %>
              </div>
              <div class="title"><strong>Alberto Savoia Can Teach You About</strong>
              </div>
            </div></a><a href="#">
            <div class="item d-flex align-items-center">
              <div class="image">
                <%= image_tag 'small-thumbnail-2.jpg', alt: '', class: 'img-fluid' %></div>
              <div class="title"><strong>Alberto Savoia Can Teach You About</strong>
              </div>
            </div></a><a href="#">
            <div class="item d-flex align-items-center">
              <div class="image">
                <%= image_tag 'small-thumbnail-3.jpg', alt: '', class: 'img-fluid' %>
              </div>
              <div class="title"><strong>Alberto Savoia Can Teach You About</strong>
              </div>
            </div></a></div>
      </div>
    </aside>
  </div>
</div>

app/views/layouts/_admin_footer.html.erb
<footer class="footer">
  <div class="d-sm-flex justify-content-center justify-content-sm-between">
    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2017 <a href="https://www.bootstrapdash.com/" target="_blank">BootstrapDash</a>. All rights reserved.</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
  </div>
</footer>

app/views/layouts/_admin_header.html.erb
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <%= link_to "The Blog", root_path %>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-stretch">

    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item nav-logout d-none d-lg-block">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link"%>
      </li>

    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="mdi mdi-menu"></span>
    </button>
  </div>
</nav>

app/views/layouts/_admin_sidebar.html.erb
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link" href="../../index.html">
        <span class="menu-title">New Post</span>
        <i class="mdi mdi-home menu-icon"></i>
      </a>
    </li>
  </ul>
</nav>

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="copyrights">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p>&copy; 2020. All rights reserved. Demo Site.</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <!-- Main Navbar-->
  <nav class="navbar navbar-expand-lg">
    <div class="search-area">
      <div class="search-area-inner d-flex align-items-center justify-content-center">
        <div class="close-btn"><i class="icon-close"></i></div>
        <div class="row d-flex justify-content-center">
          <div class="col-md-8">
            <form action="#">
              <div class="form-group">
                <input type="search" name="search" id="search" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search-1"></i></button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="navbar-header d-flex align-items-center justify-content-between">
        <%= link_to 'The Blog', root_path, class: 'navbar-brand' %>
        <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
      </div>
      <div id="navbarcollapse" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <div class="custom-control custom-switch">
              <input type="checkbox" class="custom-control-input" id="customSwitch1">
              <label class="custom-control-label" for="customSwitch1">Dark theme</label>
            </div>
          </li>
          <li class="nav-item">
            <% if current_user %>
            <%= link_to 'New Post', new_post_path, class: 'nav-link' %>
            <% end %>
          </li>
          <li class="nav-item">
            <% if current_user %>
              <%= link_to 'Logout',  destroy_user_session_path, method: :delete , class: 'nav-link' %>
            <% else %>
              <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>The Blog</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <!-- Google fonts - Open Sans-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Fancybox-->


    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-scroller">
      <% if current_user %>
        <%= render "layouts/admin_header" %>
      <% end %>
      <div class="container-fluid page-body-wrapper">
        <div class="main-panel">
          <div class="content-wrapper">
            <%= yield %>
          </div>
          <% if current_user %>
            <%= render "layouts/admin_footer" %>
          <% end %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>The Blog</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <!-- Google fonts - Open Sans-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Fancybox-->


    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/posts/_posts.html.erb
<% if posts.present? %>
  <% posts.each do |post| %>
    <div class="post col-xl-4">
      <div class="post-thumbnail">
        <%= link_to post.link, target: '_blank' do %>
          <% if post.image.present? %>
            <%= image_tag post.image, alt: '', class: 'img-fluid' %>
          <% elsif post.source.blank? && post.post_cover.present? %>
            <%= image_tag post.post_cover, alt: '', class: 'img-fluid' %>
          <% else %>
            <%= image_tag 'default_cover.png', alt: '', class: 'img-fluid' %>
          <% end %>
        <% end %>
      </div>
      <div class="post-details">
        <div class="post-meta d-flex justify-content-between">
        </div>
        <%= link_to post.link, target: '_blank' do %>
          <h3 class="h4"><%= post.title %></h3>
        <% end %>
        <p class="text-muted">
          <%= truncate(post.small_description,length: 150)%>
        </p>
        <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
            <div class="avatar">
              <%= image_tag "default_logo.png", alt: '', class: 'img-fluid' %>
            </div>
            <div class="title"><span><%= post.author || 'Manually uploaded' %></span></div></a>
          <div class="date"><i class="icon-clock"></i> <%= time_ago_in_words(post.created_at) %></div>
        </footer>
      </div>
    </div>
  <% end %>
<% else %>
  <p>No matching data found.</p>
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <main class="posts-listing col-lg-12">
      <div class="container">
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <%= form_tag post_search_path, class: 'search-form', remote: true do %>
              <div class="form-group">
                <%= text_field_tag :search, nil, placeholder: "What are you looking for?" %>
                <%= button_tag type: 'submit', class: 'submit' do %>
                  <i class="icon-search"></i>
                <% end %>
              </div>
              <div class="form-group">
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Filter Articles
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <%= link_to "Odd Articles", odd_even_filter_path(seq_filter: 'odd'), remote: true, class: "dropdown-item"%>
                    <%= link_to "Even Articles", odd_even_filter_path(seq_filter: 'even'), remote: true, class: "dropdown-item"%>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

        <div class="row" id="posts-container">
            <%= render partial: 'posts', locals: {posts: @posts}%>
        </div>
        <!-- Pagination -->
        <nav aria-label="Page navigation example">
          <%= link_to "Load more", posts_path(page: @posts.current_page+1), class: 'btn btn-secondary', id: "load-more-posts", remote: true %>
        </nav>
      </div>
    </main>
      <!-- Widget [Search Bar Widget]-->
  </div>
</div>

app/views/posts/index.js.erb
$("#posts-container").append("<%= j(render(partial: "posts", locals:{posts: @posts} )) %>");

<% if @posts.last_page? %>
  $("#load-more-posts").hide();
<% else %>
  $("#load-more-posts").attr("href", "<%= posts_path(page: (@posts.current_page+1)) %>");
<% end %>

app/views/posts/new.html.erb
<div class="row">
  <div class="offset-md-3 col-md-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Add New Post</h4>
        <p class="card-description"> Fill out the following details </p>
        <%= form_for @post, class: 'forms-sample dropzone',remote: true, html: {id: "dropzone-form-id", multipart: true } do |f| %>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div class="form-group">
            <label for="exampleInputUsername1">Title</label>
            <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
          </div>
          <div class="form-group">
            <label for="exampleInputUsername1">Short description</label>
            <%= f.text_area :small_description, class: 'form-control', placeholder: 'Small description' %>
          </div>
          <div class="form-group">
              <div id="files-field"
                  class="dropzone"
                  style="border: 2px dashed rgba(0, 0, 0, 0.3);
                         min-height: 100px !important;">
               <div class="dz-message"
                    style="margin: 20px">
                 Drag image here! Or
                 <button>
                   select files
                 </button>
               </div>
             </div>
          </div>
          <%= f.submit 'Submit', class: 'btn btn-gradient-primary mr-2' %>
          <%= button_tag 'Clear', type: :reset, class: 'btn btn-outline-primary', id: "reset_btn"%>
          <%= link_to "Cancel", root_path, class: "btn btn-light"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/odd_even_filter.js.erb
$("#posts-container").html("<%= j(render(partial: "posts", locals:{posts: @posts} )) %>");
<% if @posts.last_page? %>
  $("#load-more-posts").hide();
<% else %>
  var a = "<%= "#{posts_path({page: (@posts.current_page+1), search: @search_term})}".html_safe %>"
  $("#load-more-posts").attr("href", a);
<% end %>

app/views/posts/search.js.erb
$("#posts-container").html("<%= j(render(partial: "posts", locals:{posts: @posts} )) %>");
<% if @posts.last_page? %>
  $("#load-more-posts").hide();
<% else %>
  var a = "<%= "#{posts_path({page: (@posts.current_page+1), search: @search_term})}".html_safe %>"
  $("#load-more-posts").attr("href", a);
<% end %>